server:
  port: 9090

spring:
  application:
    name: rabbitmq-test
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true