spring:
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static,classpath:/public,classpath:/resources,classpath:/META-INF/resources

  rabbitmq:
    host: 192.168.1.150 #配置rabbitmq的地址
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true #confirm回调
    publisher-returns: true #return回调
    listener:
      simple:
        acknowledge-mode: auto
        prefetch: 1
        retry:
          max-attempts: 3
          enabled: true
          initial-interval: 2000
    cache:
      connection:
        mode: connection
        size: 10
      channel:
        size: 25
        checkout-timeout: 500

logging:
  config: classpath:config/logback-spring.xml
  level:
    com.bmsoft.dc.collect: info

mq-name: logDetails-fanout-test
mq-interval: 1000
mq-thread: 1